# Generated by Django 3.2.9 on 2022-06-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=100)),
                ('course_id', models.BigIntegerField(default=0)),
                ('stage', models.CharField(default='1', max_length=15)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descrip', models.CharField(max_length=300)),
                ('status', models.CharField(default=1, max_length=5)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('utype_id', models.BigIntegerField()),
                ('status', models.CharField(default=1, max_length=5)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('pid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('time', models.CharField(choices=[('9:30 - 10:30', '9:30 - 10:30'), ('10:30 - 11:30', '10:30 - 11:30'), ('11:30 - 12:30', '11:30 - 12:30'), ('12:30 - 1:30', '12:30 - 1:30'), ('2:30 - 3:30', '2:30 - 3:30'), ('3:30 - 4:30', '3:30 - 4:30'), ('4:30 - 5:30', '4:30 - 5:30')], default='11:30 - 12:30', max_length=50)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
            ],
            options={
                'db_table': 'meetingtime',
            },
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('fmail', models.CharField(max_length=30)),
                ('mmail', models.CharField(max_length=30)),
                ('fjob', models.CharField(max_length=30)),
                ('mjob', models.CharField(max_length=30)),
                ('fphone', models.CharField(max_length=20)),
                ('mphone', models.CharField(max_length=20)),
                ('app_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'parent',
            },
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth', models.DecimalField(decimal_places=2, max_digits=4)),
                ('twelfth', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ug', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('certificatetenth', models.CharField(max_length=100)),
                ('certificatetwelfth', models.CharField(max_length=100)),
                ('certificateug', models.CharField(max_length=100)),
                ('app_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_number', models.CharField(max_length=10)),
                ('seating_capacity', models.IntegerField(default=0)),
                ('status', models.CharField(default=1, max_length=5)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.BigIntegerField(default=0)),
                ('batch_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('dept_id', models.BigIntegerField(default=0)),
                ('photo', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=30)),
                ('login_id', models.BigIntegerField()),
                ('uid', models.CharField(default='None', max_length=10)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='utype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'utype',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=40)),
                ('max_numb_students', models.CharField(max_length=65)),
                ('subject_type', models.CharField(default='theory', max_length=10)),
                ('teachers', models.ManyToManyField(to='app.teacher')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=5)),
                ('dept_id', models.BigIntegerField()),
                ('status', models.CharField(default=1, max_length=5)),
                ('fee', models.CharField(default=25000, max_length=7)),
                ('subjects', models.ManyToManyField(to='app.subject')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='batch',
            fields=[
                ('batch_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('num_class_in_week', models.IntegerField(default=0)),
                ('class_teacher', models.BigIntegerField(default=0)),
                ('semester', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='batched', max_length=25)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('meeting_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.meetingtime')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.room')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
            options={
                'db_table': 'batch',
            },
        ),
    ]
