# Generated by Django 3.2.9 on 2022-01-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_utype'),
    ]

    operations = [
        migrations.CreateModel(
            name='utype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'utype',
            },
        ),
    ]
