# Generated by Django 3.2.9 on 2022-06-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_course_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(to='app.subject'),
        ),
    ]
