# Generated by Django 3.2.9 on 2022-06-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_course_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='dept_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
