# Generated by Django 3.2.9 on 2022-01-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='department',
        ),
    ]
