# Generated by Django 3.2.9 on 2022-06-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subject_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='pid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
