# Generated by Django 3.2.9 on 2022-01-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
