# Generated by Django 3.2.9 on 2022-07-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_teacher_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('Att_str', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'attendence',
            },
        ),
    ]
