# Generated by Django 3.2.9 on 2022-01-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_department_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(default=1, max_length=5),
        ),
    ]
