# Generated by Django 3.2.9 on 2022-01-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
    ]
