# Generated by Django 3.2.9 on 2022-07-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220717_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='studymaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_number', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('teacher_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'studymaterial',
            },
        ),
    ]
