# Generated by Django 3.2.9 on 2022-01-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default=1, max_length=5),
        ),
    ]
