# Generated by Django 3.2.9 on 2022-07-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_studymaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('problem', models.CharField(max_length=100)),
                ('teacher_id', models.BigIntegerField(default=0)),
                ('fromtime', models.DateTimeField(auto_now=True)),
                ('totime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.BigIntegerField(default=0)),
                ('answer', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'submission',
            },
        ),
    ]
