# Generated by Django 3.2.9 on 2022-07-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_assignment_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='fromtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='totime',
            field=models.DateTimeField(),
        ),
    ]
