# Generated by Django 3.2.9 on 2022-01-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dept_id',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(default=1, max_length=5),
        ),
    ]
