# Generated by Django 3.2.9 on 2022-07-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
