# Generated by Django 3.2.9 on 2022-07-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_student_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='student_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
