# Generated by Django 3.2.9 on 2022-07-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_attendence_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendancepercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.BigIntegerField()),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('attendancevalue', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'attendancepercent',
            },
        ),
    ]
