# Generated by Django 3.2.9 on 2022-01-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_login_utype_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('dept_id', models.BigIntegerField()),
                ('qualifiication', models.CharField(max_length=30)),
                ('login_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
