# Generated by Django 3.2.9 on 2022-07-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_attendancepercent'),
    ]

    operations = [
        migrations.CreateModel(
            name='internals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.BigIntegerField()),
                ('subject_number', models.CharField(max_length=10)),
                ('assignment_one', models.CharField(max_length=10)),
                ('assignment_two', models.CharField(max_length=10)),
                ('series_one', models.CharField(max_length=10)),
                ('series_two', models.CharField(max_length=10)),
                ('attendance_mark', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'internals',
            },
        ),
    ]
