# Generated by Django 3.2.9 on 2022-01-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
