# Generated by Django 3.2.9 on 2022-02-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_teacher_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
