# Generated by Django 3.2.9 on 2022-02-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_qualifiication_teacher_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dept_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
