# Generated by Django 3.2.9 on 2022-02-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('fmail', models.CharField(max_length=30)),
                ('mmail', models.CharField(max_length=30)),
                ('fjob', models.CharField(max_length=30)),
                ('mjob', models.CharField(max_length=30)),
                ('fphone', models.CharField(max_length=20)),
                ('mphone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'parent',
            },
        ),
    ]
