# Generated by Django 3.2.9 on 2022-02-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='app_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
