# Generated by Django 3.2.9 on 2022-02-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_parent_app_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth', models.DecimalField(decimal_places=2, max_digits=2)),
                ('twelfth', models.DecimalField(decimal_places=2, max_digits=2)),
                ('ug', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('certificatetenth', models.CharField(max_length=100)),
                ('certificatetwelfth', models.CharField(max_length=100)),
                ('certificateug', models.CharField(max_length=100)),
                ('app_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'record',
            },
        ),
    ]
