# Generated by Django 3.2.9 on 2022-02-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_record_ug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='tenth',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='record',
            name='twelfth',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
