# Generated by Django 3.2.9 on 2022-02-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_application_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
