# Generated by Django 3.2.9 on 2022-02-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_application_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('course_id', models.BigIntegerField(default=0)),
                ('teacher_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'batch',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.BigIntegerField(default=0)),
                ('batch_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
