# Generated by Django 3.2.9 on 2022-02-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_batch_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='semester',
            field=models.BigIntegerField(default=0),
        ),
    ]
