# Generated by Django 3.2.9 on 2022-05-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_batch_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='descrip',
            field=models.CharField(default='ahahaha', max_length=300),
            preserve_default=False,
        ),
    ]
