# Generated by Django 3.2.9 on 2022-05-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_department_descrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.CharField(default=25000, max_length=5),
        ),
    ]
