# Generated by Django 3.2.9 on 2022-05-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_course_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fee',
            field=models.CharField(default=25000, max_length=7),
        ),
    ]
